version: '2'
services:
  db:
    image: postgres:latest
    env_file: 
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  api:
    image: node:11
    depends_on: 
      - db
    ports:
      - 3001:3001
    volumes:
      - ./:/app
    working_dir: /app
    command: yarn start 
