version: "2"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "qwe-098"
      POSTGRES_DB: "typeorm-test"
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
